### ISSUE TITLE
Change from Watts–Strogatz to Barabási–Albert model.

### ISSUE THREAD

**Issue by geektoni** [geektoni/whanau-sybil-proof-DHT#5]
This will enable us to generate more realistic social network datasets.

**Comment by andreazampieri** [comment]
Added the BarabasiAlbertGraphGenerator. 
Seems like it isn't a probabilistic generator (regarding the number of edges of the nodes). See further explanation on the comments of the code and the [API description](https://jgrapht.org/javadoc/org/jgrapht/generate/BarabasiAlbertGraphGenerator.html)

**Comment by geektoni** [comment]
Cool! Thank you for doing that! It makes sense to me though since it generates scale-free networks using the preferential attachment method.
