### ISSUE TITLE
List of experiments which needs to be done

### ISSUE THREAD

**Issue by geektoni** [geektoni/whanau-sybil-proof-DHT#6]
This is the list of experiments which needs to be done in order to evaluate the algorithm:

**Number of Lookup messages used  decreases as table size increase (we assume to use just 3 layers)**
(Table size, number of nodes, percentage attack edges)
- [x] (10, 10000, 0.01)
- [x] (50, 10000, 0.01)
- [x] (100, 10000,  0.01)
- [x] (500, 10000,  0.01) 
- [x] (1000, 10000,  0.01)
- [x] (2000, 10000,  0.01)
- [x] (10, 10000, 0.1)
- [x] (50, 10000, 0.1)
- [x] (100, 10000,  0.1)
- [x] (500, 10000,  0.1) 
- [x] (1000, 10000,  0.1)
- [x] (2000, 10000,  0.1)
- [x] (10, 10000, 0.15)
- [x] (50, 10000, 0.15)
- [x] (100, 10000,  0.15)
- [x] (500, 10000,  0.15) 
- [x] (1000, 10000,  0.15)
- [x] (2000, 10000,  0.15)

**Number of lookup message used varying the percentage of attack edges (we assume to just use 3 layers and to fix the tables size to the optimal value for the network)**
(Percentage of attack edges, table size, network size)
- [x] 0.0, 100, 10000
- [x] 0.01, 100, 10000
- [x] 0.1, 100, 10000
- [x] 0.15, 100, 10000
- [x] 0.20, 100, 10000
- [x] 0.25, 100, 10000
- [x] 0.0, 320, 100000
- [x] 0.01, 320, 100000
- [x] 0.10, 320, 100000
- [x] 0.15, 320, 100000
- [x] 0.20, 320, 100000
- [x] 0.25, 320, 100000

**Number of lookup message is constant if there is no attack (the number of layers is fixed to 3)**
(Network size, table size)

- [x] 5000, 70
- [x] 10000, 100
- [x] 100000, 320
- [x] 200000, 447

**Number of layer improves quality**
(attack edges, table size, network size, layer size)
- [x] 0.0, 100, 10000, 1
- [x] 0.1, 100, 10000, 1
- [x] 0.15,  100, 10000, 1
- [x] 0.20,  100, 10000, 1
- [x] 0.25, 100, 10000, 1
- [x] 0.0, 100, 10000, 5
- [x] 0.1, 100, 10000, 5
- [x] 0.15,  100, 10000, 5
- [x] 0.20,  100, 10000, 5
- [x] 0.25, 100, 10000, 5
- [x] 0.0, 100, 10000, 7
- [x] 0.1, 100, 10000, 7
- [x] 0.15,  100, 10000, 7
- [x] 0.20,  100, 10000, 7
- [x] 0.25, 100, 10000, 7

**Comment by andreazampieri** [comment]
About the Graph generation (BarabasiAlbert method) maybe lower the number of edges added to see the impact on the performances:
- [ ] 1
- [x] 2 as a pessimistic assumption

**Comment by geektoni** [comment]
Yes, I would say 2 is good.
