### ISSUE TITLE
Fix the usage of LookupResult

### ISSUE THREAD

**Issue by andreazampieri** [geektoni/whanau-sybil-proof-DHT#7]
Now there's only one integer accumulating the number of tries and the number of messages sent around. Doesn't it make sense to insert a new counter?
NOTE: the writer on file needs the counter of tries to be 'clean' in order to work properly

Should I fix it?

**Comment by geektoni** [comment]
Ideally, we should record just the number of tries and not the number of
lookups (I mean, we need only how many queries messages were sent). So we
should not need a new counter.
